In [20]:
# from sklearn.model_selection import KFold
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.svm import SVC
# from sklearn.model_selection import train_test_split
# from sklearn.datasets import load_digits

# Data = load_digits()

In [51]:
# X_train, X_test, y_train, y_test = train_test_split(Data.data,Data.target,test_size=0.2)


In [53]:
# LogRegress = LogisticRegression(solver='saga',multi_class='multinomial')
# LogRegress.fit(X_train,y_train)
# LogRegress.score(X_test,y_test)

In [54]:
# RandForest = RandomForestClassifier(n_estimators=40)
# RandForest.fit(X_train,y_train)
# RandForest.score(X_test,y_test)

In [55]:
# SVM = SVC(gamma='scale')
# SVM.fit(X_train,y_train)
# SVM.score(X_test,y_test)

In [36]:
# from sklearn.model_selection import cross_val_score
# cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'),Data.data,Data.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [41]:
# cross_val_score(SVC(gamma='scale',C=4),Data.data,Data.target,cv=3)

array([0.96661102, 0.97829716, 0.97495826])

In [42]:
# cross_val_score(RandomForestClassifier(n_estimators=30),Data.data,Data.target,cv=3)

array([0.9115192 , 0.94991653, 0.92153589])

In [22]:
# from sklearn.model_selection import StratifiedKFold
# import numpy
# Kfold = StratifiedKFold(n_splits=3)
# Log = []
# Svm = []
# Rmf = []

# def GetScore(Model, X_train, X_test, y_train, y_test):
#     Model.fit(X_train,y_train)
#     return Model.score(X_test,y_test)

# for train_index , test_index in Kfold.split(Data.data,Data.target):
#     X_train, X_test, y_train, y_test = Data.data[train_index],Data.data[test_index] , \
#                                        Data.target[train_index],Data.target[test_index]
#     Log.append(GetScore(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
#     Svm.append(GetScore(SVC(gamma='scale'), X_train, X_test, y_train, y_test))
#     Rmf.append(GetScore(RandomForestClassifier(n_estimators=30), X_train, X_test, y_train, y_test))

# print('\nThe Cross Validation score Avarage of Logistic Regression    is :',numpy.average(Log))
# print('\nThe Cross Validation score Avarage of Support Vector Machine is :',numpy.average(Svm))
# print('\nThe Cross Validation score Avarage of Randm Forest Clasifier is :',numpy.average(Rmf))


The Cross Validation score Avarage of Logistic Regression    is : 0.9193099610461881

The Cross Validation score Avarage of Support Vector Machine is : 0.9699499165275459

The Cross Validation score Avarage of Randm Forest Clasifier is : 0.9337785197551475


In [20]:
# '''Exercise for the K-Fold And Cross Value Change'''
# import numpy
# from sklearn.datasets import load_iris
# from sklearn.model_selection import cross_val_score
# from sklearn.ensemble import RandomForestClassifier
# from sklearn import linear_model
# from sklearn import tree
# from sklearn import svm

# Data = load_iris()
# dir(Data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [32]:
# RFC_score = cross_val_score(RandomForestClassifier(),Data.data,Data.target,cv=3)
# RFC_score

array([0.98, 0.94, 0.96])

In [27]:
# LGR_Score = cross_val_score(linear_model.LogisticRegression(solver='liblinear'),Data.data,Data.target,cv=3)
# LGR_Score

array([0.96, 0.96, 0.94])

In [29]:
# DTC_score = cross_val_score(tree.DecisionTreeClassifier(),Data.data,Data.target,cv=3)
# DTC_score

array([0.98, 0.94, 1.  ])

In [31]:
# SVM_Score = cross_val_score(svm.SVC(gamma='scale'),Data.data,Data.target,cv=3)
#SVM_Score

array([0.96, 0.98, 0.94])

In [33]:
# print('\nThe Avarage of Logistric Regression Model is :{0}.'.format(numpy.average(LGR_Score)))
# print('\nThe Avarage of Random Forest Classifier Model is :{0}.'.format(numpy.average(RFC_score)))
# print('\nThe Avarage of Data Distribution Classifier Model is :{0}.'.format(numpy.average(DTC_score)))
# print('\nThe Avarage of Support vector Machine Model is :{0}.'.format(numpy.average(SVM_Score)))


The Avarage of Logistric Regression Model is :0.9533333333333333.

The Avarage of Random Forest Classifier Model is :0.96.

The Avarage of Data Distribution Classifier Model is :0.9666666666666667.

The Avarage of Support vector Machine Model is :0.96.
