In [4]:
import pandas

Data = pandas.read_csv('D:/Python/File Handling/Mail.csv')
Data.groupby('Category').describe()
Data['Spam'] = Data['Category'].apply(lambda x : 1 if x == 'spam' else 0)
Data


Category                                            Message  Spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(Data.Message,Data.Spam,test_size=0.2)
len(X_test)

1115

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

Vector = CountVectorizer()
X_train_count = Vector.fit_transform(X_train.values)
X_train_count.toarray()[0:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:

from sklearn.naive_bayes import MultinomialNB

Model = MultinomialNB()
Model.fit(X_train_count,y_train)

MultinomialNB()

In [32]:
Email = [
            'FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv',
            'Even my brother is not like to speak with me. They treat me like aids patent.',
            'As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune',
            'WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
            'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
            'I\'m gonna be home soon and i don\'t want to talk about this stuff anymore tonight, k? I\'ve cried enough today.',
            'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info',
            'URGENT! You have won a 1 week FREE membership in our £100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18',
            'I\'ve been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.',
            'I HAVE A DATE ON SUNDAY WITH WILL!!',
            'XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL'


        ]

Email_Count = Vector.transform(Email)
Model.predict(Email_Count)

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [33]:
from sklearn import pipeline

Pipe = pipeline.Pipeline([('Vector',CountVectorizer()),('Model',MultinomialNB())])
Pipe.fit(X_train,y_train)
Pipe.predict(Email)

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)